using JobCandidates.API.Common;
using JobCandidates.API.Extensions;
using JobCandidates.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi.Models;
using System.Reflection;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(swagger =>
{
    swagger.CustomSchemaIds(t => t.FullName);
    swagger.SwaggerDoc("UserProfile", new OpenApiInfo { Title = "UserProfile", Version = "UserProfile" });

    //Locate the XML file being generated by ASP.NET...
    string xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.XML";
    string xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);

    //... and tell Swagger to use those XML comments.
    swagger.IncludeXmlComments(xmlPath);
});

builder.Services.ConfigureCors(builder.Configuration);
builder.Services.InitializeApplication(builder.Configuration);


var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/UserProfile/swagger.json", "UserProfile");
    });
    app.UseDeveloperExceptionPage();

}

UpdateDatabase(app);
app.UseCors("CorsPolicy");
app.UseCustomExceptionHandler();

app.UseHttpsRedirection();

app.UseRouting();
app.UseAuthentication();


app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();


void UpdateDatabase(IApplicationBuilder app)
{
    using (var serviceScope = app.ApplicationServices
        .GetRequiredService<IServiceScopeFactory>()
        .CreateScope())
    {
        using (var context = serviceScope.ServiceProvider.GetService<JobCandidatesContext>())
        {
            context.Database.Migrate();
        }
    }
}